name: Deploy to Tomcat Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check environment variables
        run: |
          echo "SERVER_IP: ${{ secrets.SERVER_IP }}"
          echo "USERNAME: ${{ secrets.USERNAME }}"
          echo "TOMCAT_DIR: ${{ secrets.TOMCAT_DIR }}"


