name: Deploy to Tomcat Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Package compiled files
        run: |
          mkdir -p package/WEB-INF/classes
          cp -r target/classes/* package/WEB-INF/classes/
          cp -r src/main/webapp/* package/  # Adjust this path based on your webapp files location
          tar -czf package.tar.gz -C package .

      - name: List directory contents
        run: ls -la
