name: Deploy to Tomcat Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Package compiled files
        run: |
          mkdir -p package/WEB-INF/classes
          cp -r target/classes/* package/WEB-INF/classes/
          cp -r src/main/webapp/* package/  # Adjust this path based on your webapp files location

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Debug private key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key.pem
          cat private_key.pem  # Only for debugging, remove in production
          chmod 600 private_key.pem


          EOF
